env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true
  '@typescript-eslint/no-empty-interface':
    - off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - off
  quotes:
    - error
    - double
  semi:
    - error
    - always
